### PR TITLE
WIP feat: support upnp

### PR DESCRIPTION
**Pull request by Ehco1996**
auto discover local gateway and set rule listen port to upnp port

### CODE REVIEW

**Comment by gaecoli** [comment]
What else needs to do?

**Comment by Ehco1996** [comment]
> What else needs to do?

@gaecoli

I've summarized this feature in issue #330. If you're interested in contributing to the project, please feel free to submit a pull request and link it to that issue.

I'll do my best to review your PR promptly and provide any necessary context or assistance. Your contributions are highly valued, and together, we can make ehco even better for everyone.

**Comment by gaecoli** [comment]
> > What else needs to do?
> 
> @gaecoli
> 
> I've summarized this feature in issue #330. If you're interested in contributing to the project, please feel free to submit a pull request and link it to that issue.
> 
> I'll do my best to review your PR promptly and provide any necessary context or assistance. Your contributions are highly valued, and together, we can make ehco even better for everyone.

Ok, thank u!

**Comment by Ehco1996** [comment]
waiting pr

**Pull request closed without merging**
